name: Deploy Workflow
on:
  workflow_run:
    workflows: ["Test-Workflow"] # Must exactly match the 'name' field of Workflow 1
    types:
      - completed

  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: echo "Deploying to GitHub Pages... "

      - name: Output the information
        run: echo "${{ toJSON(github)}}"
